version: '3.8'

services:
  # Service MongoDB
  mongo:
    image: mongo:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - food-delivery-network

  # Service Backend
  backend:
    image: alibouabidi/food-delivery-backend:latest
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    ports:
      - "8000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/food-delivery
      - PORT=5000
      - NODE_ENV=production
      - JWT_SECRET=your_jwt_secret
    networks:
      - food-delivery-network

  # Service Frontend
  frontend:
    image: alibouabidi/food-delivery-frontend:latest
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    ports:
      - "5173:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000
    networks:
      - food-delivery-network

  # Service Admin
  admin:
    image: alibouabidi/food-delivery-admin:latest
    deploy:
      replicas: 1
    ports:
      - "5174:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000
    networks:
      - food-delivery-network

volumes:
  mongodb_data:

networks:
  food-delivery-network:
    driver: overlay
    attachable: true