apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  namespace: food-delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
      - name: admin
        image: alibouabidi/food-delivery-admin:latest
        ports:
        - containerPort: 80
        env:
        - name: VITE_API_URL
          value: "http://backend:8000"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: admin
  namespace: food-delivery
spec:
  selector:
    app: admin
  ports:
  - port: 5174
    targetPort: 80
  type: LoadBalancer